services:
  - type: web
    name: authservice
    env: docker
    plan: free
    dockerfilePath: ../Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Issuer
        value: https://authservice-93h8.onrender.com
      - key: Jwt__Audience
        value: https://authservice-93h8.onrender.com
      - key: Jwt__Key
        value: thisismySecretKey0Lo9iKj87T4Rf6yHj
      - key: ConnectionStrings__DefaultConnection
        value: "Server=<RENDER_DB_HOST>;Database=AccountDB;User=<RENDER_DB_USER>;Password=<RENDER_DB_PASSWORD>;"
    healthCheckPath: /
    autoDeploy: true